updating read the docs

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -42,19 +42,11 @@ jobs:
               mkdir -p "$(dirname "$target_file")"
 
               # Get the base name of the .man file to use as the title
-              title=$(basename "$man_file" .man)
+              base_name=$(basename "$man_file" .man)
 
               # Convert the .man file to .rst
-              pandoc -f man "$man_file" -s -o "$target_file" 2>/dev/null || echo "Error processing $man_file"
+              pandoc -f man "$man_file" -s -o "$target_file" -V title="$base_name" 2>/dev/null || echo "Error processing $man_file"
 
-              # Ensure the .rst file was created successfully before modifying it
-              if [ -f "$target_file" ]; then
-                # Prepend the title to the .rst file
-                echo "$title" | cat - "$target_file" > temp && mv temp "$target_file"
-                echo "$(echo "$title" | sed 's/./=/g')" >> "$target_file"  # Underline the title
-              else
-                echo "Error: $target_file not created."
-              fi
             done
           else
             echo "docs/man is not empty, checking for modified .man files"
