updating read the docs

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -45,11 +45,21 @@ jobs:
               base_name=$(basename "$man_file" .man)
               
               # Convert the .man file to .rst
-              pandoc -f man -t rst "$man_file" -s -o "$target_file" --metadata title=$base_name 2>/dev/null || echo "Error processing $man_file"
+              pandoc -f man -t rst "$man_file" -s -o "$target_file" --metadata title="$base_name" 2>/dev/null || echo "Error processing $man_file"
             done
           else
             echo "docs/man is not empty, checking for modified .man files"
-            git diff --name-only HEAD^ HEAD | grep "\.man$" | while IFS= read -r modified_man; do
+            # Check if the current commit has a parent (HEAD^) and avoid errors in shallow repositories
+            if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
+              # If there is a parent commit, compare with HEAD^
+              modified_man_files=$(git diff --name-only HEAD^ HEAD | grep "\.man$")
+            else
+              # Otherwise, compare with the previous commit (first commit scenario)
+              modified_man_files=$(git diff --name-only HEAD~1 HEAD | grep "\.man$")
+            fi
+
+            # Process each modified .man file
+            echo "$modified_man_files" | while IFS= read -r modified_man; do
               target_file="docs/man/$(echo "$modified_man" | sed 's|^ldms/src/||;s|^ldms/man/||;s/\.man$/.rst/')"
 
               # Ensure the target directory exists
@@ -59,7 +69,7 @@ jobs:
               base_name=$(basename "$modified_man" .man)
 
               # Convert the .man file to .rst
-              pandoc -f man -t rst "$modified_man" -s -o "$target_file" --metadata title=$base_name 2>/dev/null || echo "Error processing $modified_man"
+              pandoc -f man -t rst "$modified_man" -s -o "$target_file" --metadata title="$base_name" 2>/dev/null || echo "Error processing $modified_man"
 
             done
           fi
@@ -67,7 +77,7 @@ jobs:
       - name: Update index.rst files only if changes to .man files
         run: |
           # Check for changes in .man files using git status
-          modified_man_files=$(git status --porcelain | awk '/\.man$/ {print $2}')
+          modified_files=$(git status --porcelain "$docs_man_dir" | grep -E '^\s*(M|A)\s+.*\.man$' | awk '{print $2}')
 
           # If no .man files have been modified, exit the script
           if [ -z "$modified_man_files" ]; then
